config/routes.rb
SylviaZaich::Application.routes.draw do
  resources :galleries do
    resources :paintings
  end

  resources :paintings do
    resources :images
  end

  root :to => "static#home"

  match 'about' => "static#about", :via => :get

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
   attr_accessible :name, :description
   extend FriendlyId
   friendly_id :name, :use => :slugged

   has_many :paintings

   validates_presence_of :name
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :painting_id, :asset
  belongs_to :painting

  has_attached_file :asset, 
    :styles => {:small => "200x", :thumb => "200x134>", :full => "x600"},
    :path => "image/:attachment/:style/:id.:extension"

  validates_attachment_presence :asset
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :description, :gallery, :name
  extend FriendlyId
  friendly_id :name, :use => :slugged

  has_many :images
  belongs_to :gallery

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_galleries

  private
    def find_galleries
      @galleries = Gallery.find(:all)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_filter :find_gallery, :only => [:show, :edit, :update]
  def show
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      flash[:success] = "Product created successfully."
      redirect_to edit_gallery_path(@gallery)
    else
      flash[:error] = "Fix error in gallery form."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @gallery.update_attributes(params[:gallery])
      flash[:success] = "Updated successfully."
      redirect_to edit_gallery_path(@gallery)
    else
      flash[:error] = "Fix error in gallery form."
      render 'edit'
    end
  end

  def find_gallery
    @gallery = Gallery.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @painting = Painting.find(params[:painting_id])
    @image = Image.new
    render 'new', :layout => "iframe" if params[:iframe]
  end

  def create
    @painting = Painting.find(params[:painting_id])
    @image = @painting.images.new(params[:image])
    if @image.save
      redirect_to new_painting_image_path(@painting, :iframe => true)
    else
      render 'new'
    end
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_filter :find_gallery
  before_filter :find_painting, :only => [:show, :edit, :update]
  def show
  end

  def new
    @painting = @gallery.paintings.new
    respond_to do |f|
      f.js {}
    end
  end

  def create
    @painting = @gallery.paintings.new(params[:painting])
    if @painting.save
      @image = Image.new
      respond_to do |f|
        f.js { render 'create'}
      end
    else
      respond_to do |f|
        f.js { render 'errors'}
      end
    end
  end

  def edit
  end

  def update
  end

  private

    def find_gallery
      @gallery = Gallery.find(params[:gallery_id])
    end

    def find_painting
      @painting = Painting.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  def render_modal(title, body, object)
    render 'shared/modal', :title => title, :body => body, :object => object
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/galleries/_form.html.haml
= form_for @gallery, :html => {:class => ""} do |f|
  .control-group
    = f.label :name, :class => "control-label"
    = f.text_field :name, :class => "input-xxlarge"
  .control-group
    = f.label :description, :class => "control-label"
    = f.text_area :description, :rows => 6, :class => "input-xxlarge"
  .control-group
    = f.submit :class => "btn btn-large btn-success"

app/views/galleries/edit.html.haml
%h1 Edit #{@gallery.name} Gallery

= render 'form'

%hr

.clearfix
  %h2.pull-left Paintings
  = link_to "Add Painting", new_gallery_painting_path(@gallery), :class => "btn btn-success pull-right btn-large", :remote => true, :id => "add-image"
%ul.paintings.unstyled
  - @gallery.paintings.each do |painting|
    %li.clearfix
      %h4=painting.name
      %ul.unstyled
        - painting.images.each do |image|
          %li.pull-left.span3
            = image_tag(image.asset.url(:small))
    %hr

app/views/galleries/new.html.haml
%h1 Create new Gallery

= render 'form'

app/views/galleries/show.html.haml
%h1 Galleries#show
%p Find me in app/views/galleries/show.html.haml

app/views/images/_form.html.haml
= form_for [@painting, @image], :html => { :multipart => true, :class => 'form-inline' } do |f|
  .clearfix
    .fileupload.fileupload-new.pull-left{:'data-provides' => "fileupload"}
      .input-append
        .uneditable-input{:style => "width: 200px"}
          %span.fileupload-preview
        %span.btn.btn-file
          %span.fileupload-new
            Select file
          %span.fileupload-exists
            Change 
          = f.file_field :asset
        = link_to "Remove", "#", :class => "btn fileupload-exists", :'data-dismiss' => "fileupload"
    = f.submit "Upload Image", :class => "btn btn-success pull-right"



      

app/views/images/_iframe.html.haml
.modal-body
  %iframe{:src => "#{new_painting_image_path(@painting, :iframe => true)}", :frameborder => "0", :vspace => "0", :hspace => "0", :webkitAllowFullScreen => "true", :mozallowfullscreen => "true", :allowFullScreen => "true", :height => '500px', :width => '100%'}
.modal-footer
  .control-group
    = link_to "I'm finished", edit_gallery_path(@painting.gallery), :class => "btn btn-large"

      

app/views/images/new.html.haml
= render 'form'
%hr
%ul.unstyled.clearfix
  - @painting.images.each do |image|
    %li.pull-left.span2
      = image_tag(image.asset.url(:small))

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  = render 'shared/meta'
  %body
    .container-fluid

      .row-fluid
        .span3.sidebar-nav
          = link_to "SZ", root_path, :class => "brand"     
          %ul.nav.nav-list
            =render 'shared/galleries'
            %li= link_to "About", about_path, :class=> 'about'
          = render 'shared/about_snippet'
          = render 'shared/twitter_btn'
        .span8.offset3.main
          = render 'shared/flash', :flash => flash
          = yield
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/iframe.html.haml
!!! 5
%html(lang="en")
  = render 'shared/meta'
  %body
    = yield
    = javascript_include_tag "application"

app/views/paintings/_form.html.haml
= form_for [@gallery, @painting], :remote => true do |f|
  .modal-body
    .control-group
      = f.label :name, :class => "control-label"
      = f.text_field :name, :class => "input-block-level", :placeholder => "name of painting"
    .control-group
      = f.label :description, :class => "control-label"
      = f.text_area :description, :rows => 6, :class => "input-block-level", :placeholder => "a short description of the painting"
  .modal-footer
    .control-group
      = f.submit "Add Painting", :class => "btn btn-large btn-success pull-right"

app/views/paintings/create.js.erb
var modalId = '#modal_<%= "#{@painting.class}" %>'
$(modalId).modal('hide');
$(modalId).remove();
$('body').append('<%= j(render_modal("Add images to #{@painting.name}", "images/iframe", @painting)) %>');
$(modalId).modal();

app/views/paintings/new.js.erb
var modalId = '#modal_<%= "#{@painting.class}" %>'
$(modalId).remove();
$('body').append('<%= j(render_modal("Add New Painting", "form", @painting)) %>');
$(modalId).modal();

app/views/shared/_about_snippet.html.haml
= image_tag('sylvia-zaich.jpg', :class => "bio-hs")
%p.bio-snippet
  Hi, I’m 
  %strong
    Sylvia Zaich. 
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.

app/views/shared/_flash.html.haml
- flash.each do |key, message|
  = content_tag :div, message, :class => "alert alert-#{key}"

app/views/shared/_galleries.html.haml
- @galleries.each do |gallery|
  %li{:class => "#{ request.path == gallery_path(gallery) ? 'active' : ''}"}
    =link_to gallery.name, gallery_path(gallery)

app/views/shared/_meta.html.haml
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title= content_for?(:title) ? "#{yield(:title)} | Sylvia Zaich" : "Sylvia Zaich"
  = csrf_meta_tags
  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
  = stylesheet_link_tag "application", :media => "all"
  %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
  %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
  %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
  %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
  %link(href="favicon.ico" rel="shortcut icon")

app/views/shared/_modal.html.haml
.modal{:id => "modal_#{object.class}"}
  .modal-header
    %button{:class => "close", :'data-dismiss' => "modal", :'aria-hidden' => true, :type => "button"}
      &times;
    %h3 
      = title
  = render body

app/views/shared/_twitter_btn.html.erb
<a href="https://twitter.com/sylpz" class="twitter-follow-button" data-show-count="false">Follow @sylpz</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>